# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3dbdc9a772af4a7e3a0c1245fd0a3b2c123fd5d9d98a5fce00c3f8ddb1a0985c42d06f0f6d0cdf64abebec424b9a64ce0b9d44a83115ad1c47e5e3b84a146d2

test:
  secret_key_base: 009c28039d0f0be91508cafb66f8a3c4b35b7ea766541339e88e90d99862af445ead0c6ad0ea4789e2b46792b4dae4d81f5f0206e49f48f3f6027adedddc5560

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
